FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.csproj .
RUN dotnet restore

# copy and publish app and libraries
COPY . .
#RUN dotnet publish -o /app --no-restore

# final stage/image
#FROM mcr.microsoft.com/dotnet/runtime:5.0
WORKDIR /source
#COPY --from=build /app .
#ENTRYPOINT ["dotnet", "dotnetapp.dll"]
